### ISSUE TITLE
Reload imported local dependencies

### ISSUE THREAD

**Issue by Jav3k** [RedisGears/RedisGears#541] opened 2021-04-26 10:34 UTC
Hi. 

My redis gears code, executed via to RG.PYEXECUTE, imports my own local python script, stored on server with redis, as a python module.  
But if i update the code of this local script, RedisGears will still use old version of local script. 

I read about [Isolation Techniques](https://github.com/RedisGears/RedisGears/blob/ed10294edb4ff8e06f9b53c03b6d730b0377e82d/docs/isolation.md). And it says: 

> Though this isolation is sufficient in most cases, it isn't perfect. The biggest shortcoming of this approach is importing modules: all executions that import a module X will get the same instance of module X. This means that even if we create a virtual environment per execution with a different implementation of module X, all of the executions will use the implementation imported first.

Is there any way to update dependencies without rebooting or restarting redis-server?

Possible duplicate of https://github.com/RedisGears/RedisGears/issues/443

**Comment by MeirShpilraien** [comment] 2021-04-27 17:14
@Jav3k sorry but currently its not possible and the only way it will be possible is using subinterpreters (which comes with its own limitation as you read in the docs). We do plane to introduce subinterpreters again (as an option if the user wants it) but I do not know yet when this will be available.

My suggestion is to put a code that might change a lot in the python code that you send on the RG.PYEXECUTE command and then there will be  no need to restrat the server. Once the code gets stable you can move it to be a dependency.

**Comment by Jav3k** [comment] 2021-04-27 20:06
@MeirShpilraien, thanks for your reply. Should I close the issue or leave it open?

**Comment by MeirShpilraien** [comment] 2021-05-09 08:29
I believe it's a duplicate of this one: https://github.com/RedisGears/RedisGears/issues/443
so I am closing, reopen if you think otherwise.

**Closed** 2021-05-09 08:29 UTC
