### ISSUE TITLE
potential memory leak on JVM plugin

### ISSUE THREAD

**Issue by tomerhekredis** [RedisGears/RedisGears#674] opened 2022-01-18 14:14 UTC
Running `RG.JDUMPSESSIONS` will show us 2 sessions, but the first (id 0) will never get deleted:
```
root@4ddfef3d948a:/build# redis-cli
127.0.0.1:6379> RG.JDUMPSESSIONS
1) "active"
2) 1)  1) "id"
       2) "0000000000000000000000000000000000000000-0"
       3) "mainClassName"
       4) "com.redislabs.WriteBehind"
       5) "version"
       6) (integer) 103
       7) "jar"
       8) "/build/-jars/6dd4bf5b1013c1c6ebe90606f82c43045413d898.jar"
       9) "refCount"
      10) (integer) 0
   2)  1) "id"
       2) "0000000000000000000000000000000000000000-4"
       3) "mainClassName"
       4) "com.redislabs.WriteBehind"
       5) "version"
       6) (integer) 103
       7) "jar"
       8) "/build/-jars/2b18527f3e9fe4e6e461d3235cde4e9bc12b8aa8.jar"
       9) "refCount"
      10) (integer) 5
3) "ts"
4) (empty array)
```
Even when running `RG.JRUNGC` unused sessions will be removed except this id-0.

Adding heap logs from the machine in the attached file
[jvm-heap-logs.zip](https://github.com/RedisGears/RedisGears/files/7889674/jvm-heap-logs.zip)
.

**Comment by MeirShpilraien** [comment] 2022-01-28 12:58
@tomerhekredis I believe this is due to weak reference which is less cleaned, I could reproduce it (I believe) and by running with low memory configurations and execute GC it was eventually cleaned. Closing for now. Will reopen with we find out its not solved.

**Closed by MeirShpilraien** 2022-01-28 12:58 UTC
Labels: bug
